# Use the official Node.js image as the base image
FROM node:18


# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Expose the port your app will run on
EXPOSE 6001

# Run migration and start app
CMD ["/bin/sh", "-c", "npm run db:migrate:deploy && sleep 3 && npx prisma db seed && sleep 3 && npm run start:dev"]
