-- AlterTable
ALTER TABLE "spaces" ADD COLUMN     "map_h" DOUBLE PRECISION DEFAULT 80,
ADD COLUMN     "map_w" DOUBLE PRECISION DEFAULT 120,
ADD COLUMN     "map_x" DOUBLE PRECISION,
ADD COLUMN     "map_y" DOUBLE PRECISION;
