-- AlterTable
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "total_area_sqm" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "year_built" INTEGER;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
